import 'package:expense_manager/providers/expense_provider.dart';
import 'package:intl/intl.dart';

final List<Expense> expensesData = [
  Expense(
    transactionId: '1',
    accountId: '1',
    amount: 100.00,
    category: 'Groceries',
    transactionDate: DateTime.now(),
    description: 'Supermarket purchase',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '2',
    accountId: '2',
    amount: 50.00,
    category: 'Transport',
    transactionDate: DateTime.now(),
    description: 'Gas station',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '3',
    accountId: '3',
    amount: 75.00,
    category: 'Dining',
    transactionDate: DateTime.now(),
    description: 'Restaurant bill',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '4',
    accountId: '4',
    amount: 30.00,
    category: 'Entertainment',
    transactionDate: DateTime.now(),
    description: 'Movie tickets',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '5',
    accountId: '5',
    amount: 150.00,
    category: 'Utilities',
    transactionDate: DateTime.now(),
    description: 'Electricity bill',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '6',
    accountId: '6',
    amount: 200.00,
    category: 'Rent',
    transactionDate: DateTime.now(),
    description: 'Monthly rent',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '7',
    accountId: '7',
    amount: 20.00,
    category: 'Miscellaneous',
    transactionDate: DateTime.now(),
    description: 'Stationery',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '8',
    accountId: '8',
    amount: 250.00,
    category: 'Shopping',
    transactionDate: DateTime.now(),
    description: 'Clothing',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '9',
    accountId: '9',
    amount: 500.00,
    category: 'Insurance',
    transactionDate: DateTime.now(),
    description: 'Car insurance',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '10',
    accountId: '10',
    amount: 100.00,
    category: 'Healthcare',
    transactionDate: DateTime.now(),
    description: 'Doctor\'s appointment',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '11',
    accountId: '11',
    amount: 60.00,
    category: 'Groceries',
    transactionDate: DateTime.now(),
    description: 'Supermarket purchase',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '12',
    accountId: '12',
    amount: 80.00,
    category: 'Transport',
    transactionDate: DateTime.now(),
    description: 'Gas station',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '13',
    accountId: '13',
    amount: 45.00,
    category: 'Dining',
    transactionDate: DateTime.now(),
    description: 'Restaurant bill',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '14',
    accountId: '14',
    amount: 35.00,
    category: 'Entertainment',
    transactionDate: DateTime.now(),
    description: 'Concert tickets',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
  Expense(
    transactionId: '15',
    accountId: '15',
    amount: 90.00,
    category: 'Utilities',
    transactionDate: DateTime.now(),
    description: 'Water bill',
    key: DateFormat("E dd/MM/yy").format(DateTime.now()),
  ),
];
